#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Minicli\App;
$config = require('config.php');

$app = new App($config);

$app->setSignature("Minichat for Twitch.\n./minichat twitch");
$app->runCommand($argv);
